//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Droid_Geography.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Droid_Geography.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AF; 16.63;        ///AL; 11.58;        ///DZ; 158.97;AlgŽrie        ///AO; 85.81;land, ëles        ///AG; 1.1;Afghanistan        ///AR; 351.02;Antarctique        ///AM; 8.83;        ///AU; 1219.72;Argentine        ///AT; 366.26;Argentine        ///AZ; 52.17;land, ëles        ///BS; 7.54;Belgique        ///BH; 21.73;Belize        ///BD; 105.4;Bangladesh        ///BB; 3.96;Azerba•djan        ///BY; 52.89;Belize        ///BE; 461.33;Bahre•n        ///BZ; 1.43;Belize        ///BJ; 6.49;Azerba•djan        ///BT; 1.4;Belize        ///BO; 19.18;Belize        ///BA; 16.2;        ///BW; 12.5;Belize        ///BR; 2023.53;Belize        ///BN; 11.96;Belize        ///BG; 44.84;        ///BF; 8.67;Bermudes        ///BI; 1.47;Belize        ///KH; 11.36;Kazakhstan        ///CM; 21.88;Canada        ///CA;  [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string countries {
            get {
                return ResourceManager.GetString("countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=11&quot; /&gt; 
        ///    &lt;title&gt;jVectorMap demo&lt;/title&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; media=&quot;all&quot; href=&quot;D:/Download/bjornd-jvectormap-2.0.4-0-ga0e5497/bjornd-jvectormap-a0e5497/jquery-jvectormap.css&quot; /&gt;
        ///    &lt;script src=&quot;D:/Download/bjornd-jvectormap-2.0.4-0-ga0e5497/bjornd-jvectormap-a0e5497/src/jquery-1.8.2.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;D:/Download/bjornd-jvectormap-2.0.4-0-ga0e5497/bjornd-jvectormap-a0e5497/jquery-jvectormap.js&quot;&gt;&lt;/sc [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string worldmap {
            get {
                return ResourceManager.GetString("worldmap", resourceCulture);
            }
        }
    }
}
